[[redirects]]
  from = "/home"
  to = "https://imwzx.netlify.app/"
  status = 301
  force = true

[[redirects]]
  from = "/link"
  to = "https://imwzx.netlify.app/link"
  status = 301
  force = true

[[redirects]]
  from = "/game"
  to = "https://imwzx.netlify.app/game"
  status = 301
  force = true

[[redirects]]
  from = "/go"
  to = "https://imwzx.netlify.app/go"
  status = 301
  force = true

[[redirects]]
  from = "/post/about"
  to = "https://imwzx.netlify.app/post/about"
  status = 301
  force = true
